Feature/african facts
geordyd/migrai pull request #4
Opened 2023-03-12 16:09 UTC by MignonGakuba

Created the logical of the african-facts function

2023-03-14 19:45 UTC, geordyd commented on africanfacts/africanFacts.go
> +	}
This should be a separate function

2023-03-14 19:45 UTC, geordyd commented on africanfacts/africanFacts.go
> +	x := rand.Intn(max-min) + min
This should also be a function, because it is also used in the giveRandomFactCategoryAfricanFactsByCategory function

2023-03-14 19:45 UTC, geordyd commented on africanfacts/africanFacts.go
> +	var catergoryList = []string{"geography", "wildlife", "demographics", "language", "economy", "nature"}
We could get these dynamically, but lets put that on the todo list

2023-03-14 19:45 UTC, geordyd commented on africanfacts/africanFacts.go
> +}
lets maybe just use one struct and just remove this one?

2023-03-14 19:56 UTC, geordyd requested changes

2023-03-14 19:56 UTC, geordyd commented on africanfacts/africanFacts.go
> +	}
This list could be a slice, we already talked about this.

2023-03-14 19:56 UTC, geordyd commented on africanfacts/africanFacts.go
> +		log.Fatal("Error when opening file: ", err)
log.Fatal will call os.Exit(1), which will in turn kill the bot. We should think about how we are going to return the errors.

2023-03-14 19:56 UTC, geordyd commented on main.go
> +		_, err := s.ChannelMessageSend(m.ChannelID, "```Available commands:\n - !help\n - !timeleft\n - !link\n - !changelog - !link\n - !african-facts random```")
There should only be one ```!link\n``` in there.

2023-03-20 14:20 UTC, MignonGakuba commented on africanfacts/africanFacts.go
> +		log.Fatal("Error when opening file: ", err)
Sooo what is your suggestion?

2023-03-20 14:20 UTC, MignonGakuba commented on africanfacts/africanFacts.go
> +		log.Fatal("Error when opening file: ", err)
Give please a example

2023-03-20 19:11 UTC, geordyd requested changes
Needs some work,  I am not able to run it yet. 
Also can you run ```go mod tidy``` in the project?

2023-03-20 19:11 UTC, geordyd commented on africanfacts/africanFacts.go
> +	max := len(factCategory.ArrayFactsCategory)
This is always 0, which always makes ```x := rand.Intn(max-min) + min```  on line 84 panic.
You can read about it here in the docs: https://pkg.go.dev/math/rand#Intn.

2023-03-20 19:20 UTC, geordyd commented on africanfacts/africanFacts.go
> +}
Ok, lets do this in the next version.
You could make a function like this:
```
func readJson() []FactCategory {

	jsonFile, err := os.Open("facts.json")
	if err != nil {
		fmt.Println(err)
	}

	fmt.Println("Successfully Opened facts.json!")
	defer jsonFile.Close()

	content, err := io.ReadAll(jsonFile)
	if err != nil {
		log.Fatal("Error when opening file: ", err)
	}

	var facts []FactCategory

	err = json.Unmarshal(content, &facts)
	if err != nil {
		log.Fatal("Error during Unmarshal(): ", err)
	}

	return facts
}
```
You will need to change the structure of the JSON file to an array that contains all the objects for this to work.

2023-03-23 08:29 UTC, merged